version: '3.8'

services:
  mysql1:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "123456"
      MYSQL_DATABASE: "spring_batch"
    container_name: spring-batch-database
    restart: always

  mysql2:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "123456"
      MYSQL_DATABASE: "credit_card_bill"
    volumes:
      - ./files/scripts_application:/docker-entrypoint-initdb.d
    container_name: application-database
    restart: always
